### ISSUE TITLE
大佬，请问这个 如何能支持 类似于小游戏的支持呢？以及有几个疑问

### ISSUE THREAD

**Issue by gamegg** [zhengfasheng/QuickFramework#2]
大佬，请问这个 如何能支持 类似于小游戏的支持呢？

1.现在的2.4 分支很棒，但是我测试了下，web是能够正常预览的，而微信小游戏是 不能加载 子游戏 的，提示jsb错误；
而如果我们比如做很多小游戏集合就 不好操作了，请问 这个如何处理呢？感谢！

2.现在的 2.4 分支 已经有 官方内置bundle支持了，那个 给引擎打补丁包的操作还需要来一次吗？

3. 热更新引擎我 刚测试了下，有几次生成不了，可能是我的操作不对吗？热更新的 mainfest存储目录 是不能更改的吗（比如 热更新的资源 都可以放在 项目目录下的某个文件夹下，这样会不会更完美）？
个人意见哈！~

**Comment by zhengfasheng** [comment]
1，目前是一个项目开发，所有目前的方式就是开发自己游戏时，可以删除掉其它游戏再打开creator
2,引擎补丁包，是需要的，后面加强下插件，给个提示
3，哪个manifest目录，可以更改，不过你需要自己定制下相应的代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gamegg"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 中午11:58
收件人: "TopDiscover/QuickFramework"<QuickFramework@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TopDiscover/QuickFramework] 大佬，请问这个 如何能支持 类似于小游戏的支持呢？以及有几个疑问 (#2)





 
大佬，请问这个 如何能支持 类似于小游戏的支持呢？
 
1.现在的2.4 分支很棒，但是我测试了下，web是能够正常预览的，而微信小游戏是 不能加载 子游戏 的，提示jsb错误；
 而如果我们比如做很多小游戏集合就 不好操作了，请问 这个如何处理呢？感谢！
 
2.现在的 2.4 分支 已经有 官方内置bundle支持了，那个 给引擎打补丁包的操作还需要来一次吗？
  
热更新引擎我 刚测试了下，有几次生成不了，可能是我的操作不对吗？热更新的 mainfest存储目录 是不能更改的吗（比如 热更新的资源 都可以放在 项目目录下的某个文件夹下，这样会不会更完美）？
 个人意见哈！~

**Comment by gamegg** [comment]
> 1，目前是一个项目开发，所有目前的方式就是开发自己游戏时，可以删除掉其它游戏再打开creator 2,引擎补丁包，是需要的，后面加强下插件，给个提示 3，哪个manifest目录，可以更改，不过你需要自己定制下相应的代码
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gamegg"<notifications@github.com&gt;; 发送时间: 2020年7月15日(星期三) 中午11:58 收件人: "TopDiscover/QuickFramework"<QuickFramework@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [TopDiscover/QuickFramework] 大佬，请问这个 如何能支持 类似于小游戏的支持呢？以及有几个疑问 (#2) 大佬，请问这个 如何能支持 类似于小游戏的支持呢？ 1.现在的2.4 分支很棒，但是我测试了下，web是能够正常预览的，而微信小游戏是 不能加载 子游戏 的，提示jsb错误； 而如果我们比如做很多小游戏集合就 不好操作了，请问 这个如何处理呢？感谢！ 2.现在的 2.4 分支 已经有 官方内置bundle支持了，那个 给引擎打补丁包的操作还需要来一次吗？ 热更新引擎我 刚测试了下，有几次生成不了，可能是我的操作不对吗？热更新的 mainfest存储目录 是不能更改的吗（比如 热更新的资源 都可以放在 项目目录下的某个文件夹下，这样会不会更完美）？ 个人意见哈！~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢~

**Comment by zhengfasheng** [comment]
这个问题已经处理完成，需要更新下

**Comment by gamegg** [comment]
> 这个问题已经处理完成，需要更新下

感谢！~

**Comment by zhengfasheng** [comment]
简书地址： https://www.jianshu.com/p/6d878adbf0bf
