### ISSUE TITLE
这个在 android下无法正常加载子游戏

### ISSUE THREAD

**Issue by gamegg** [zhengfasheng/QuickFramework#3]
1.最新的这个2.4版本，我测试下，web和微信小游戏 都能正常打开 运行；

2.但是在 android 真机下 无法加载子游戏：真机下 大厅都是正常能加载的，子游戏one和two都不能正常加载
（我的环境是：android 26、NDK 为android-ndk-r21b、SDK为Android studio 4里面集成的）

很奇怪，我就提个issue吧。

**Comment by zhengfasheng** [comment]
你去我简书看下https://www.jianshu.com/p/6d878adbf0bf，是不是少了什么步骤

**Comment by zhengfasheng** [comment]
你去我简书看看是不是少了什么步骤https://www.jianshu.com/p/6d878adbf0bf

**Comment by zhengfasheng** [comment]
是不是子游戏没部署到服务器，或者部署了服务器，没开起来，不然你先按我简书的环境跑一下

**Comment by gamegg** [comment]
> 是不是子游戏没部署到服务器，或者部署了服务器，没开起来，不然你先按我简书的环境跑一下

是我的问题，没有修改 源代码 \assets\script\common\base\HotUpdate.ts 的TEST_HOT_UPDATE_URL_ROOT 值 造成的，

有几个疑问：
1.打包Android的界面中，“资源服务器地址” 需要填写吗？
2.当能正常打开子游戏后，关闭真机里面的游戏后，我把工程里面的大厅prefab修改了点文字内容，然后修改了 “热更新工具”的 大厅版本号为10（上次的为1），然后“生成”，然后 “部署”，按道理 重启游戏后 能够自动更新内容吗？ 可是我这里没有更新成功，额，奇怪，查不到问题的原因

**Comment by zhengfasheng** [comment]
ok
