### ISSUE TITLE
测试发现，有2个问题：A热更新不起作用   B打包没有移除GameTwo

### ISSUE THREAD

**Issue by gamegg** [zhengfasheng/QuickFramework#4]
测试发现：

A. 子游戏功能都正常加载，但是热更新不起作用
apk在真机能够正常测试，后来我把工程里面的大厅prefab修改了点文字内容，然后修改了 “热更新工具”的 大厅版本号为10（上次的为1），然后“生成”，然后 “部署”，按道理 重启游戏后 能够自动更新内容吗？ 可是我这里没有更新成功；
后面测试了2个子游戏 修改内容，并按正常流程步骤发布 热更新包，依旧无法在 真机和模拟器 里面更新，还是老的内容和代码

B. gameone 和 gametwo都打包在游戏apk包里了
Quick-debug.apk\assets\assets\   中 gameOne和gameTwo都在包里面，
已经配置过这2个bundle为Android的bundle了，其次在 \packages\config\games.json也配置了如下的内容：
`{
    "packageUrl":"http://192.168.0.10/hotupdate",
    "forceIncludeAllGameToApk": false,
    "games":[
        {  "id" : "0"    , "name" : "大厅"     , "dir" : ""          , "version" : "1" , "includeApk" : true },
        {  "id" : "1"    , "name" : "游戏1"    , "dir" : "gameOne"   , "version" : "1" , "includeApk" : true },
        {  "id" : "2"    , "name" : "游戏2"    , "dir" : "gameTwo"   , "version" : "1" , "includeApk" : false }
    ]
}`
貌似不生效

这2个问题，我是仔细测试过了，生怕出错，所以多测试编译了几次，结果错误依旧，希望大神不吝赐教，感谢感谢！

**Comment by zhengfasheng** [comment]
大厅没有写更新逻辑，这边自己补上，api在[](https://github.com/TopDiscover/QuickFramework/blob/2.4.0/assets/script/common/base/HotUpdate.ts#L318)

**Comment by zhengfasheng** [comment]
大厅没有更新逻辑，需要自己补全,大厅更新的[API](https://github.com/TopDiscover/QuickFramework/blob/2.4.0/assets/script/common/base/HotUpdate.ts#L318)

**Comment by zhengfasheng** [comment]
那个更新不了的问题，已经ok了

**Comment by zhengfasheng** [comment]
测试这个更新，你首先是先生成最新的俩个版本（2，3），先都部署到你的服务器上，然后再生成一个最低版本为1的，这个版本只生成，不部署，可直接修改TEST_HOT_UPDATE_URL_ROOT去指向你的2，先升级到2，再修改TEST_HOT_UPDATE_URL_ROOT去指向你的3，升级到3

**Comment by zhengfasheng** [comment]
TEST_HOT_UPDATE_URL_ROOT的修正可直接在生成的build/jsb-default/assets/main/index.js中修改，就没必要去重新构建项目了

**Comment by gamegg** [comment]
> TEST_HOT_UPDATE_URL_ROOT的修正可直接在生成的build/jsb-default/assets/main/index.js中修改，就没必要去重新构建项目了

好的，非常感谢，我来测试下！

**Comment by gamegg** [comment]
> 测试这个更新，你首先是先生成最新的俩个版本（2，3），先都部署到你的服务器上，然后再生成一个最低版本为1的，这个版本只生成，不部署，可直接修改TEST_HOT_UPDATE_URL_ROOT去指向你的2，先升级到2，再修改TEST_HOT_UPDATE_URL_ROOT去指向你的3，升级到3

经过 仔细测试发现：
1.游戏第一次能够正常加载 远程子游戏分包（注意：微信小游戏 需要上传文件夹 remote 到 远程服务器上才行），
2. 后面如果 子游戏 更新了资源文件和版本号（热更新工具操作的），然后打开app 发现，一直卡在
“
执行更新 gameTwo 
正在更新游戏，请稍等   assets/main/index.2104f.js:2052 
”
无法完成 子游戏的新版本 更新逻辑

我这测试了 微信小游戏 和 android 26 这2个平台



另：
1.我今天额外看了下框架和代码，写的很优雅，特别是自动注入；
2.希望能够完善下 protobuf或者其他如json 网络层的相关封装；
如果 后面能够配套一些视频、文档资料，做个比较完善的demo（客户端+服务端），降低学习和初期项目的门槛，我相信肯定有人买和学习的
3.现在很多游戏方面的都转 学习类 产品了，你的这个框架真的很好，感谢！

**Comment by alfred-lijun** [comment]
我的理解是，这个框架是大厅和子游戏一起开发，子游戏开发完了版本，构建的时候其实大厅也构建了新版本，旧的大厅是支持不了这个新的子游戏的，需要把大厅也热更新到子游戏构建时的版本才行。所以其实没法做到子游戏的单独更新

**Comment by zhengfasheng** [comment]
问题已经处理了，到新的地址上去，之后更新在新的仓库: https://gitee.com/top-discover/QuickFramework
